### ISSUE TITLE
internal server error at first start

### ISSUE THREAD

**Issue by a1mersnow** [nuxt/learn.nuxt.com#90]
I'm experiencing the error after starting the dev server:
```
Internal server error: Soft-invalidated module "/node_modules/.pnpm/nuxt@3.9.0_eslint@8.56.0_typescript@5.3.3_vite@5.0.10_vue-tsc@1.8.27/node_modules/nuxt/dist/app/entry.js" should not have existing transform result

[nitro] [unhandledRejection] TypeError: Cannot read properties of null (reading '_file')
    at ReactiveEffect.fn (/Users/a1mer/f/learn.nuxt.com/components/PanelDocs.vue:39:131)
    at ReactiveEffect.run (/Users/a1mer/f/learn.nuxt.com/node_modules/.pnpm/@vue+reactivity@3.3.13/node_modules/@vue/reactivity/dist/reactivity.cjs.js:162:19)
    at get value [as value] (/Users/a1mer/f/learn.nuxt.com/node_modules/.pnpm/@vue+reactivity@3.3.13/node_modules/@vue/reactivity/dist/reactivity.cjs.js:1138:33)
    at unref (/Users/a1mer/f/learn.nuxt.com/node_modules/.pnpm/@vue+reactivity@3.3.13/node_modules/@vue/reactivity/dist/reactivity.cjs.js:1021:29)
    at Object.get (/Users/a1mer/f/learn.nuxt.com/node_modules/.pnpm/@vue+reactivity@3.3.13/node_modules/@vue/reactivity/dist/reactivity.cjs.js:1027:35)
    at _sfc_ssrRender (/Users/a1mer/f/learn.nuxt.com/components/PanelDocs.vue:70:16)
    at renderComponentSubTree (/Users/a1mer/f/learn.nuxt.com/node_modules/.pnpm/@vue+server-renderer@3.3.13_vue@3.3.13/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:685:9)
    at renderComponentVNode (/Users/a1mer/f/learn.nuxt.com/node_modules/.pnpm/@vue+server-renderer@3.3.13_vue@3.3.13/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:631:12)
    at renderVNode (/Users/a1mer/f/learn.nuxt.com/node_modules/.pnpm/@vue+server-renderer@3.3.13_vue@3.3.13/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:745:14)
    at renderVNodeChildren (/Users/a1mer/f/learn.nuxt.com/node_modules/.pnpm/@vue+server-renderer@3.3.13_vue@3.3.13/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:761:5)
```
It don't influence the functions of the website.
And, if I reload the page, the error will disappear.

The occurence pattern:
If I have opened `http://localhost:3000`, then restart the dev server, I'll give this error immediately.

If I haven't opened `http://localhost:3000`, then I need to reload once or twice to see this error.

However, it will disappear after reloading the page unless I restart the dev server.

There are two errors in the console, later `Cannot read properties of null` is a new one.
The first error has been there for a bit long period.

**Comment by antfu** [comment]
Can't reproduce, do you have the same error with: https://learn-nuxt-com.netlify.app/ ?

**Comment by a1mersnow** [comment]
No, it's dev only. It's weird because I never see it in your live stream...

**Comment by a1mersnow** [comment]
I reinstalled the deps, the problem had just gone away...
